### ISSUE TITLE
wptsync-bot often makes gratuitous reordering modifications

### ISSUE THREAD

**Issue by docfaraday** [mozilla/wpt-sync#1076]
Examples include reordering the set of expected outcomes, and reordering lines in meta files. Here's an example: 

https://hg.mozilla.org/mozilla-central/diff/c7a5382fb11a4cda81a0a3499fc0ea0f4ef066e4/testing/web-platform/meta/webrtc/RTCDataChannel-bufferedAmount.html.ini#l1.81

These kinds of modifications make it difficult to track down when expectations were modified.

**Comment by jgraham** [comment]
This is actually a bug in the metadata update code (which is in m-c rather than the sync itself). I've submitted https://bugzilla.mozilla.org/show_bug.cgi?id=1796603
