### ISSUE TITLE
Retriggered jobs don't show up in Treeherder

### ISSUE THREAD

**Issue by mjzffr** [mozilla/wpt-sync#172]
`TaskclusterClient.retrigger` does indeed retrigger jobs, and their results show in the Task Inspector and the taskgroup-completed Pulse message, but those updates don't get picked up by Treeherder. Makes failure inspection difficult.

**Comment by jgraham** [comment]
This was fixed by https://github.com/mozilla/wpt-sync/commit/88fb3595e9d6807ad4589da2f4bd3f4d89e17601
