### ISSUE TITLE
Patch being upstreamed to w3c should not result in new Bug or try pushes

### ISSUE THREAD

**Issue by mjzffr** [mozilla/wpt-sync#18]
Here's an example of a patch that landed on autoland: the bot opened a w3c PR (good) then also a new bug (bad) and made try pushes for the bug (bad) -- https://bugzilla.mozilla.org/show_bug.cgi?id=1437889

The expected behaviour for a change being upstreamed is to only open a w3c PR.

**Comment by jgraham** [comment]
So the way this is supposed to work is that we create the upstream PR and set a PR id on the sync object. Then when we get a PR notification we check if there's an upstream sync for that PR and if there is we ignore the pull request. So maybe there's some code path that isn't doing that check? In any case we could check if the PR looks like something we upstreamed before creating a downstream sync for it.

**Comment by mjzffr** [comment]
Looking through the logs, the code path where we find an upstream sync was never hit. It could be race condition between creating the PR and creating/updating the upstream sync. Or maybe we were running `wptsync update-tasks` at the time and that followed some other path -- I don't see that for now. Either way, as you say, we could also do an extra check before creating the downstream sync: e.g. make sure the PR sender not moz-wptsync-bot.

**Comment by mjzffr** [comment]
Should be fixed in https://github.com/mozilla/wpt-sync/pull/49
