### ISSUE TITLE
Needinfo users when upstream sync fails

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#1808]
We currently add a message indicating that fixup is required from a wpt-sync admin, but don't actually alert those admins. I think historically we hoped that we could needinfo the sync bot, and subscribe to that needinfo list, but it doesn't seem to work. Instead we should needinfo the list of admins from the configuration file.

**Comment by lutien** [comment]
That seems to be working now: https://bugzilla.mozilla.org/show_bug.cgi?id=1841692#a2904031_611017
