### ISSUE TITLE
Some upstream PRs are not merged.

### ISSUE THREAD

**Issue by emilio** [mozilla/wpt-sync#19]
See https://github.com/w3c/web-platform-tests/pull/9478 and the corresponding bug, which is on central since more than a day ago.

**Comment by emilio** [comment]
@bzbarsky also mentioned https://bugzilla.mozilla.org/show_bug.cgi?id=1437255#c6 and https://bugzilla.mozilla.org/show_bug.cgi?id=1169290#c101 over IRC.

**Comment by jgraham** [comment]
I think this is working  better now, but please feel free to reopen if there are more problems.
