### ISSUE TITLE
If upstream PRs get closed without merge, bugs aren't closed as well

### ISSUE THREAD

**Issue by whimboo** [mozilla/wpt-sync#219]
If there is an upstream PR a new bug has been created for (like https://bugzilla.mozilla.org/show_bug.cgi?id=1492636), wpt-sync doesn't seem to close the bug when the upstream PR gets closed.

**Comment by jgraham** [comment]
This should be fixed by https://github.com/mozilla/wpt-sync/commit/9a430fda71bedb40e00f87198f2840768cdf315e
