### ISSUE TITLE
Sub test entry not removed for downstream sync even without any remaining expectations left

### ISSUE THREAD

**Issue by whimboo** [mozilla/wpt-sync#2377]
Over on https://hg.mozilla.org/integration/autoland/rev/21ea92b7e4cf we had a new test passing and the expectation for `FAIL` was removed. But somehow the sub test entry including the bug reference remained:

```diff
 [viewport.py]
   disabled:
     if os == "android": bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1840084
-
   [test_with_scrollbars[quirks-both\]]
     bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1819490
-    expected: FAIL
```

Given that this was the one and only expectation entry the `[test_with_scrollbars[quirks-both\]]` entry should have been completely removed.

**Comment by lutien** [comment]
It looks like it's actually `wpt-update` issue. I managed to reproduce it locally just with this command without the bot being involved. I've created a bug for it: https://bugzilla.mozilla.org/show_bug.cgi?id=1921499.
