### ISSUE TITLE
wptsync service doesn't start up properly if pid files not cleaned up

### ISSUE THREAD

**Issue by mjzffr** [mozilla/wpt-sync#25]
I just restarted `wptsync listen` because it looked up but inactive. Judging by the start-up logs, I don't think it really started in the first place because the workspace had left-over *.pid files. That's my theory anyway.

**Comment by jgraham** [comment]
I suspect that what's going on here is that we don't actually send the `SIGTERM` to the celery processes; we just exit the `listen` script and exit the docker container, preventing clean shutdown. We probably want to use `trap` to forward the signal to the `celery` processes, wait for them to shut down, and then exit.
