### ISSUE TITLE
Missing comment on Bugzilla for manual merges

### ISSUE THREAD

**Issue by whimboo** [mozilla/wpt-sync#371]
As noticed on https://bugzilla.mozilla.org/show_bug.cgi?id=1477977#c19 when a manual merge happens no Bugzilla comment will be added. Interestingly we had something similar for the bot in issue #286.

**Comment by dhdavvie** [comment]
I believe I have found the issue. The merge message is posted if the status of the sync is not marked as "complete" [here](https://github.com/mozilla/wpt-sync/blob/master/sync/upstream.py#L953). However if [UpstreamSync.update_github](https://github.com/mozilla/wpt-sync/blob/master/sync/upstream.py#L351) is called and notices the pr is merged, it will mark the sync status as "complete". So if update_github is called before update_pr, the status will be marked as "complete" and therefore "update_pr" won't do anything about it. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1558197 looks like a similar case where the PR was manually merged but the merge comment was posting, which seems to support my theory.

The fix would probably need to be made in update_github, as it looks like its setting the sync.status too wildly without checking if anything else needs to be done. 

cc @jgraham thoughts?

**Comment by jgraham** [comment]
It's not clear to me in which situation we end up calling `update_github` without calling `update_pr`, but certainly we can change `update_github` to ensure that we always comment on the bug before we change the status. Should probably wrap up the "notify and mark as done" logic in a method.

**Comment by dhdavvie** [comment]
I'm not sure either, but it looks like it would be the culprit as its the only place in UpstreamSync that the status is moved to "complete". It might make sense to change the functionality of `.finish()` to also handle the notification of the state change? Will look into it

**Comment by dhdavvie** [comment]
Closing this as #419 should've resolved this.
