### ISSUE TITLE
Multiple PR merged messages

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#377]
See e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1306999 It's unclear why the sync is even trying to merge that more than once, but certainly it shouldn't re-comment if the PR is already closed.

**Comment by dhdavvie** [comment]
It looks like this and #371 are related. If update_pr entry point is called multiple times with a "closed" action whilst the sync status is set to "wpt-merged", it will just continue to comment that the PR has been merged and mark itself (again) as "wpt-merged".

**Comment by dhdavvie** [comment]
Closing this as #419 should've resolved this
