### ISSUE TITLE
bot created a new landing before previous one reached central

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#397]
https://bugzilla.mozilla.org/show_bug.cgi?id=1568505 was created whilst https://bugzilla.mozilla.org/show_bug.cgi?id=1567435 was still on inbound. We should be waiting until it reaches central to create a new landing.

**Comment by dhdavvie** [comment]
Do we have any logs from this?

**Comment by jgraham** [comment]
I believe this stopped happening when we changed how we recogised upstream PRs from looking at the metadata to actually indexing them by PR id and using that index. Let's reopen if we see any more similar failures.
