### ISSUE TITLE
Please license this repository or make it private.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/wpt-sync#4]
Hi! I wasn't able to determine what LICENSE this repository is intended to operate under from an inspection of the files in the root directory. Since it's a public repository, it needs to be clearly licensed; please add a LICENSE file for whatever you consider appropriate (Mozilla's default would be MPL2 here), or alternately mark this repository private if it's not intended to be open source. Thanks!

**Comment by jgraham** [comment]
8941c19fa59ee9ae1a4c4e4ce7f6dd79f68e4884
