### ISSUE TITLE
Seeing a lot of unexplained mach failures

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#466]
This is happening trying to update metadata.

c.f. https://rpm.newrelic.com/accounts/1872822/applications/43012201/filterable_errors#/show/c168b5ab-ca57-11e9-8523-0242ac110008_0_6599/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart

It would be good to figure out root causes here as this is a thing that blocks sync from being landing-ready. The first step would be to improve the logging so that the underlying mach error ends up being recorded rather than (or in addition to) the resulting stack in the sync code.

**Comment by dhdavvie** [comment]
https://rpm.newrelic.com/accounts/1872822/applications/43012201/traced_errors/81ff6065-d9fb-11e9-b4ad-0242ac110007_0_6932

Unfortunately this didn't seem to help, as the output gets truncated by NR. Could try printing the tail end of the output, but again this may just cut out useful information. Do we have an alternative place to log this? We could log it and manually check the logs on the server but that seems like a painful process.

**Comment by jgraham** [comment]
OK, so running things interactively it seems like we sometimes end up with corrupted caches in the `~/.mozbuild/` directory. That seems like it could be a wpt issue but maybe we should delete that directory in the cleanup, or when we get an error.

**Comment by dhdavvie** [comment]
This is addressed in #500.
