### ISSUE TITLE
Upstream sync thinks that PRs have merge conflicts when actually they just aren't approved.

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#53]
We try to merge PRs immediately after creating them, which doesn't work that well because the bot that auto-approves them hasn't run yet and so they look unmergable to us, and we end up commenting that there's a merge conflict on the bugs. We should explicitly test for approval and if it's missing just do nothing.

**Comment by mjzffr** [comment]
Wait for https://github.com/mozilla/wpt-sync/pull/57
