### ISSUE TITLE
The get_pr_sync function sometimes fails to find upstream PRs

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#61]
https://rpm.newrelic.com/accounts/1872822/applications/43012201/filterable_errors#/show/db3de4f4-17dc-11e8-8799-0242ac110007_0_3907/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart&_k=pd3tzv

It isn't clear if this is because the function is failing to find a thing that exists, or because the thing that ought to exist doesn't.

**Comment by mjzffr** [comment]
i.e. why do we need that extra workaround for bugs we're upstreaming
