### ISSUE TITLE
Auto-file bugs for clear issues

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#7]
We have one bug per sync, but that's somewhat transient and should be closed when the pr is landed on central. But for some cases we know with high confidence that something's an issue that should be tracked:
* Crashes
* Regressions where tests used to pass
* Unstable tests

In these cases we could file a separate bug (at most one per class per sync) to track the problem.

**Comment by jgraham** [comment]
cc @bzbarsky

**Comment by jgraham** [comment]
17:55 <@bkelly> jgraham: I would like a bug for new test failures

cc @wanderview

**Comment by wanderview** [comment]
My rationale is that we at least need to investigate it.  Maybe we will close the bug after that investigation or maybe we need to fix something.  That fix could be in gecko or upstream, etc.  Having a bug to track that would be very helpful.  Thanks.

**Comment by mjzffr** [comment]
Might need a list of components where this is enabled, e.g. DOM
