### ISSUE TITLE
Remove use of six

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#796]
Now that we are Py3-only we can remove use of the six library and instead use the Python 3 native idioms everywhere.

**Comment by geegatomar** [comment]
Hello, Can I please take this up?

**Comment by jgraham** [comment]
@geegatomar  I think this can be done in an automated way using [pyupgrade](https://github.com/asottile/pyupgrade). I tried that a bit in https://github.com/mozilla/wpt-sync/pull/1117 but apparently it didn't quite work first time. It could be worth just retrying that approach on latest master, and figure out any resulting test failures, rather than doing it by hand.
