### ISSUE TITLE
Intermittents cause incorrect metadata during landings

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#96]
When we do a landing, we do a full metadata update. That is needed because results may have changed due to gecko-side changes since the PR metadata was generated. But if there's an intermittent in that try run we'll land the "wrong" metadata for the intermittent.

We could do something like rescheduling failing jobs, or querying treeherder to find out which failures are likely intermittent.

**Comment by AutomatedTester** [comment]
could we do a verify type job on the whole suit to solve this?

**Comment by AutomatedTester** [comment]
> could we do a verify type job on the whole suit to solve this?

speaking to @jgraham this would be a really poor use of resource because not all intermittents are test related.

**Comment by mjzffr** [comment]
Addressed in #126
